"""Repository contracts for the three auth-flow token tables, satisfied
structurally by :mod:`app.modules.auth.repositories.sqlalchemy.token_repository`."""

from __future__ import annotations

import uuid
from typing import Protocol

from app.modules.auth.models import EmailVerificationToken, PasswordResetToken, RefreshToken


class RefreshTokenRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> RefreshToken | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[RefreshToken]: ...

    def add(self, instance: RefreshToken) -> None: ...

    async def delete(self, instance: RefreshToken) -> None: ...

    async def list_active_for_user(self, user_id: uuid.UUID) -> list[RefreshToken]: ...

    async def revoke_family(self, family_id: uuid.UUID) -> None: ...

    async def revoke_all_for_user(self, user_id: uuid.UUID) -> None: ...


class PasswordResetTokenRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> PasswordResetToken | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[PasswordResetToken]: ...

    def add(self, instance: PasswordResetToken) -> None: ...

    async def delete(self, instance: PasswordResetToken) -> None: ...

    async def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...


class EmailVerificationTokenRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> EmailVerificationToken | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[EmailVerificationToken]: ...

    def add(self, instance: EmailVerificationToken) -> None: ...

    async def delete(self, instance: EmailVerificationToken) -> None: ...

    async def get_by_token_hash(self, token_hash: str) -> EmailVerificationToken | None: ...
