"""Repository contracts for :class:`~app.modules.organizations.models.Organization`
and :class:`~app.modules.organizations.models.OrganizationInvitation`,
satisfied structurally by
:mod:`app.modules.organizations.repositories.sqlalchemy.organization_repository`."""

from __future__ import annotations

import uuid
from typing import Protocol

from app.infrastructure.database.associations import UserOrganizationRole
from app.modules.organizations.models import Organization, OrganizationInvitation


class OrganizationRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> Organization | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[Organization]: ...

    def add(self, instance: Organization) -> None: ...

    async def delete(self, instance: Organization) -> None: ...

    async def get_by_slug(self, slug: str) -> Organization | None: ...

    async def list_for_user(self, user_id: uuid.UUID) -> list[Organization]: ...

    async def get_membership(
        self, organization_id: uuid.UUID, user_id: uuid.UUID
    ) -> UserOrganizationRole | None: ...

    async def list_members(self, organization_id: uuid.UUID) -> list[UserOrganizationRole]: ...

    def add_membership(self, membership: UserOrganizationRole) -> None: ...

    async def remove_membership(self, membership: UserOrganizationRole) -> None: ...

    async def count_owners(self, organization_id: uuid.UUID) -> int: ...


class OrganizationInvitationRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> OrganizationInvitation | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[OrganizationInvitation]: ...

    def add(self, instance: OrganizationInvitation) -> None: ...

    async def delete(self, instance: OrganizationInvitation) -> None: ...

    async def get_by_token_hash(self, token_hash: str) -> OrganizationInvitation | None: ...

    async def get_pending_for_org_and_email(
        self, organization_id: uuid.UUID, email: str
    ) -> OrganizationInvitation | None: ...

    async def list_pending_for_org(self, organization_id: uuid.UUID) -> list[OrganizationInvitation]: ...
