"""Repository contracts for :class:`~app.modules.tenants.models.Tenant` and
the Organization<->Tenant link, satisfied structurally by
:mod:`app.modules.tenants.repositories.sqlalchemy.tenant_repository`."""

from __future__ import annotations

import uuid
from typing import Protocol

from app.infrastructure.database.associations import OrganizationTenant
from app.modules.tenants.models import Tenant


class TenantRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> Tenant | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[Tenant]: ...

    def add(self, instance: Tenant) -> None: ...

    async def delete(self, instance: Tenant) -> None: ...

    async def get_by_slug(self, slug: str) -> Tenant | None: ...


class OrganizationTenantRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> OrganizationTenant | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[OrganizationTenant]: ...

    def add(self, instance: OrganizationTenant) -> None: ...

    async def delete(self, instance: OrganizationTenant) -> None: ...

    async def get_link(
        self, organization_id: uuid.UUID, tenant_id: uuid.UUID
    ) -> OrganizationTenant | None: ...

    async def list_for_organization(self, organization_id: uuid.UUID) -> list[OrganizationTenant]: ...

    async def list_for_tenant(self, tenant_id: uuid.UUID) -> list[OrganizationTenant]: ...

    def add_link(self, link: OrganizationTenant) -> None: ...

    async def remove_link(self, link: OrganizationTenant) -> None: ...
