"""Repository contracts for :class:`~app.modules.roles.models.Role` and
:class:`~app.modules.roles.models.UserRole`, satisfied structurally by
:mod:`app.modules.roles.repositories.sqlalchemy.role_repository`."""

from __future__ import annotations

import uuid
from typing import Protocol

from app.modules.roles.models import Role, UserRole
from app.modules.users.models import User


class RoleRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> Role | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[Role]: ...

    def add(self, instance: Role) -> None: ...

    async def delete(self, instance: Role) -> None: ...

    async def get_by_code(self, code: str) -> Role | None: ...

    async def get_by_code_in_org(self, organization_id: uuid.UUID, code: str) -> Role | None: ...

    async def get_by_name_in_org(self, organization_id: uuid.UUID, name: str) -> Role | None: ...

    async def list_all_global(self) -> list[Role]: ...

    async def search_catalog(
        self,
        *,
        organization_id: uuid.UUID | None,
        search: str | None = None,
        is_system: bool | None = None,
        is_active: bool | None = None,
        limit: int = 20,
        offset: int = 0,
    ) -> tuple[list[Role], int]: ...

    async def count_permissions(self, role_id: uuid.UUID) -> int: ...

    async def count_users(self, role: Role) -> int: ...

    async def list_users(self, role: Role) -> list[User]: ...

    async def is_in_use(self, role_id: uuid.UUID) -> bool: ...

    async def get_with_permissions(self, role_id: uuid.UUID) -> Role | None: ...


class UserRoleRepository(Protocol):
    async def get_by_id(self, entity_id: uuid.UUID) -> UserRole | None: ...

    async def list_all(self, *, limit: int = 100, offset: int = 0) -> list[UserRole]: ...

    def add(self, instance: UserRole) -> None: ...

    async def delete(self, instance: UserRole) -> None: ...

    async def get(self, user_id: uuid.UUID, role_id: uuid.UUID) -> UserRole | None: ...

    async def has_role(self, user_id: uuid.UUID, role_id: uuid.UUID) -> bool: ...

    async def list_for_user(self, user_id: uuid.UUID) -> list[UserRole]: ...
